### ISSUE TITLE
The repository link for this extension returns 404

### ISSUE THREAD

**Issue by sfsaccone** [jeremyrajan/vscode-exts#103]
Hi, this isn't a bug, just thought you should know that the in VS Code the URL for the _Repository_ link is:

https://github.com/remicass/vscode-exts/tree/master/browsersync

which returns a 404.  The same is true for the same link on the [Marketplace page](https://marketplace.visualstudio.com/items?itemName=jeremyrajan.browsersync), which is:

https://github.com/jeremyrajan/vscode-exts/tree/master/browsersync

Perhaps it should be this?

https://github.com/jeremyrajan/vscode-exts/tree/master/extensions/browsersync

**Comment by jeremyrajan** [comment]
oh shoot! thanks :)

**Comment by jeremyrajan** [comment]
This has been updated, thanks :)
https://marketplace.visualstudio.com/items?itemName=jeremyrajan.browsersync
