### ISSUE TITLE
error with the Webpack Create command

### ISSUE THREAD

**Issue by LucieCamille** [jeremyrajan/vscode-exts#176]
I just installed the Webpack extenion on VSCode and tried to used it with the command palette but it trhow me an error message: "Command 'Webpack Create' resulted in an error (command 'extension.createConfig' not found)"

**Details of what I've done**
1. I installed the extension
2. I created a folder with no file in it
3. I used the command palette and found the Webpack Create command
4. Error message
5. I tried again after runing the command:
npm init -y
npm install webpack webpack-cli --save-dev
6. Got the error again

**Expected behavior**
I thought it would create a webpack.config file, with a basic configuration in it.

**Screenshots**
![image](https://user-images.githubusercontent.com/85353941/200517011-93dd533e-49fe-444c-ba25-fe37f281b2ad.png)

**Environment:**
 - OS: Windows_NT x64 10.0.19043
 - VSCODE Version: 1.73.0
 - NodeJs: 16.14.2

**Comment by jeremyrajan** [comment]
Thanks for reporting! Let me take a look :)

**Comment by b1c1jones** [comment]
Me too.

**Comment by jeremyrajan** [comment]
Sorry for the delayed response! 

I tried it locally and it seems to work for me. I am on

```
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:01.965Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

**Comment by jeremyrajan** [comment]
Ok my fault. When I run it in dev environment it works perfectly fine. But published ext seems to be behaving different. Let me take a look :)

**Comment by jeremyrajan** [comment]
Ok! Should be fixed now. Please install `v3.0.2` and let me know. Thanks :)
