### ISSUE TITLE
Browser-sync External URL

### ISSUE THREAD

**Issue by arsari** [jeremyrajan/vscode-exts#28]
Hi,

I like a lot the extension since I don't need to open my terminal to run the CLI.

However, it is possible to show the external URL as we see the localhost URL?

This will propel a lot the use of the extension.

**Comment by jeremyrajan** [comment]
Hi @arsari,
Glad you like the extension. Sure, let me give it a shot. Will keep you posted.

Cheers,
Jeremy

**Comment by jeremyrajan** [comment]
@arsari, updated the extension to include external url, please take a look at Changelog for browsersync extension and update :) https://marketplace.visualstudio.com/items?itemName=jeremyrajan.browsersync
